[project]
name = "stenography"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "librosa>=1.0.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.2",
]

[project.scripts]
stenography = "stenography:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
